### ISSUE TITLE
Provide on-chain helper function to compute `H(params)`

### ISSUE THREAD

**Issue by fleupold** [rndlabs/composable-cow#17]
In order to cancel a Composable CoW order one has to compute `H(params)` and pass this into the `remove` method. Whereas everything else can be fairly easily done using the Safe UI (and potentially a tool to encode calldata), computing this hash is non trivial and could therefore benefit from a helper view function that makes this computable via the Etherscan UI.

**Comment by mfw78** [comment]
With regards to this, it was envisioned that the `H(params)` is made available in an event that is emitted when a single order is created using `create()`.

It's fair that this would require the client to use `eth_getLogs` / some indexing service in order to retrieve the corresponding `bytes32` and may make UX / client-side development a little more cumbersome / heavy lifting.

Additionally, creating this helper function, and using with `remove` is single-order specific (ie. this functionality isn't required when using merkle-trees).

**Comment by fleupold** [comment]
Agree that this is not strictly needed at all.

Practically speaking though from having debugged CoW Swap orders in the settlement contract for the last two years, while it's trivial to write hashing code for order params in the language of your choice, it's much more convenient (and except for deployment gas at no additional cost) to provide a solidity helper that is exposed via etherscan so that a user can compute the hash of a given target order (e.g. to debug cases in which the event wasn't emitted because some validation failed beforehand).
I ended up deploying helper contracts for CoW Settlements afterwards to be able to offer this
